Travel/Travel/Travel/Areas/Admin/Controllers/AdminImgHotelsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using Travel.Helpper;
using Travel.Models;

namespace Travel.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]

    public class AdminImgHotelsController : Controller
    {
        private readonly dbTravelAndHotelContext _context;
        public INotyfService _notyfService { get; }

        public AdminImgHotelsController(dbTravelAndHotelContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }
        // GET: Admin/AdminImgHotels

        public IActionResult Index(int? id, int page = 1)
        {
            var pageNumber = page;
            var pageSize = 10;

            List<ImgHotel> lsImgHotel = new List<ImgHotel>();

            //if (hotelid == null)
            //{
            //    lsImgHotel = _context.ImgHotels
            //    .AsNoTracking()
            //    .OrderBy(x => x.ImgHotelId)
            //    .Include(x => x.Hotel)
            //    .ToList();
            //}
            //else

            if (id == null)
            {
                _notyfService.Error("Không được xem tất cả hình ảnh");
                return RedirectToAction("Index", "AdminHotels");
            }


            lsImgHotel = _context.ImgHotels
            .AsNoTracking()
            .OrderBy(x => x.ImgHotelId)
            .Include(x => x.Hotel)
            .Where(x => x.HotelId == id)
            .ToList();

            PagedList<ImgHotel> models = new PagedList<ImgHotel>(lsImgHotel.AsQueryable(), pageNumber, pageSize);

            ViewBag.Hotelid = id;

            Hotel hotel = _context.Hotels
               .FirstOrDefault(m => m.HotelId == id);

            ViewBag.NameHotel = hotel.Name;
            ViewBag.CurrentPage = pageNumber;
            ViewBag.PageLength = (int)Math.Ceiling((Double)lsImgHotel.Count / (Double)pageSize);
            return View(models);
        }



        // GET: Admin/AdminImgHotels/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return Redirect("/admin/AdminImgHotels?id=" + id);
            }

            ViewBag.Hotelid = id;
            Hotel hotel = _context.Hotels
               .FirstOrDefault(m => m.HotelId == id);

            ViewBag.NameHotel = hotel.Name;
            return View();
        }

        // POST: Admin/AdminImgHotels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            ImgHotel imgHotel = new ImgHotel();
            imgHotel.HotelId = id;

            if (fThumb != null)
            {
                string extension = Path.GetExtension(fThumb.FileName);
                string imagename = Path.GetRandomFileName();
                string image = imagename + extension;
                imgHotel.Description = await Utilities.UploadFile(fThumb, @"ImgHotels", image.ToLower());


                if (string.IsNullOrEmpty(imgHotel.Description)) imgHotel.Description = "default.jpg";

                _context.Add(imgHotel);
                await _context.SaveChangesAsync();
                return Redirect("/admin/AdminImgHotels?id=" + id);
            }

            _notyfService.Error("Đã xảy ra lỗi");
            ViewBag.Hotelid = id;
            Hotel hotel = _context.Hotels
               .FirstOrDefault(m => m.HotelId == id);

            ViewBag.NameHotel = hotel.Name;
            return View();
        }


        // POST: Admin/AdminImgHotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ImgHotels == null)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return Redirect("/admin/");
            }
            var imgHotel = await _context.ImgHotels.FindAsync(id);

            int hotelid = imgHotel.HotelId;

            if (imgHotel != null)
            {
                _context.ImgHotels.Remove(imgHotel);
            }

            await _context.SaveChangesAsync();
            return Redirect("/admin/AdminImgHotels?id=" + hotelid);
        }

        private bool ImgHotelExists(int id)
        {
            return _context.ImgHotels.Any(e => e.ImgHotelId == id);
        }
    }
}

Travel/Travel/Travel/Areas/Admin/Views/AdminImgHotels/Create.cshtml
@model Travel.Models.ImgHotel

@{
    ViewData["Title"] = "Thêm mới";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-action="Index" asp-controller="Home" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ quản trị</a>
            <a asp-action="Index" asp-controller="AdminHotels" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home"></i> Quản lý khách sạn</a>
            <a asp-route-id="@ViewBag.Hotelid" asp-action="Details" asp-controller="AdminHotels" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home"></i> @ViewBag.NameHotel</a>
            <a href="/admin/AdminImgHotels?id=@ViewBag.Hotelid" class="breadcrumb-item"><i class="anticon anticon-picture"></i> Hình ảnh Khách sạn</a>
            <span class="breadcrumb-item active"><i class="anticon anticon-plus-circle"></i> @ViewData["Title"]</span>
        </nav>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label>Hình ảnh</label>
                <input name="fThumb" type="file" class="form-control-file" />
            </div>

            <div class="form-row">
                <div class="btn-group">
                    <button class="btn btn-success btn-tone m-r-5">
                        <i class="anticon anticon-save"></i>
                        <span>Lưu</span>
                    </button>

                    <a class="btn btn-primary btn-tone m-r-5" href="/admin/AdminImgHotels?id=@ViewBag.Hotelid">
                        <i class="anticon anticon-backward"></i> Trở lại
                    </a>
                </div>
            </div>

        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Travel/Travel/Travel/Areas/Admin/Views/AdminImgHotels/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<Travel.Models.ImgHotel>

@{
    ViewData["Title"] = "Hình ảnh";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    int PageCurrent = ViewBag.CurrentPage;
    int PageLength = ViewBag.PageLength;
    int PageBack = PageCurrent - 1;
    int PageNext = PageCurrent + 1;
    int PageNextPlus = PageNext + 1;
    int PageNextMinus = PageBack - 1;
} 


<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-action="Index" asp-controller="Home" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ quản trị</a>
            <a asp-action="Index" asp-controller="AdminHotels" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home"></i> Quản lý khách sạn</a>
            <a asp-route-id="@ViewBag.Hotelid" asp-action="Details" asp-controller="AdminHotels" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home"></i> @ViewBag.NameHotel</a>
            <span class="breadcrumb-item active"><i class="anticon anticon-picture"></i></i> @ViewData["Title"] (@PageCurrent/@PageLength trang)</span>
        </nav>
    </div>
</div>


<div class="card">
    <div class="card-body">

        <div class="m-t-25">
            <div class="table-responsive">
                <a class="btn btn-success" asp-area="Admin" asp-controller="AdminImgHotels" asp-action="Create" asp-route-id="@ViewBag.Hotelid">
                    <i class="anticon anticon-plus-circle m-r-5"></i> <span>Thêm mới</span>
                </a>
                <table class="table">
                    <thead class="text-center">
                        <tr>
                            <th scope="col">Hình ảnh</th>
                            <th scope="col">#</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        @foreach (var item in Model)
                        {

                            <tr>
                                <th scope="row">
                                    <img width="250px" src="~/images/ImgHotels/@item.Description" alt="@item.ImgHotelId" />
                                    </th>
                                <td>

                                    <a class="btn btn-danger btn-tone m-r-5" data-toggle="modal" data-target="#Modal_@item.ImgHotelId">
                                        <i class="anticon anticon-delete"></i>Xóa
                                    </a>
                                </td>
                            </tr>

                            <!-- Modal -->
                            <div class="modal fade" id="Modal_@item.ImgHotelId">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="ModalLabel">Bạn có chắc chắn muốn xóa</h5>
                                            <button type="button" class="close" data-dismiss="modal">
                                                <i class="anticon anticon-close"></i>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            ID: @item.ImgHotelId
                                        </div>
                                        <div class="modal-footer">
                                            <form asp-action="Delete" asp-controller="AdminImgHotels" asp-area="Admin" asp-route-id="@item.ImgHotelId">
                                                <input type="hidden" />

                                                <button type="submit" value="Delete" class="btn btn-danger btn-tone m-r-5">
                                                    <i class="anticon anticon-delete"></i>
                                                    <span>Xóa</span>
                                                </button>

                                                <a class="btn btn-primary btn-tone m-r-5" data-dismiss="modal">
                                                    <i class="anticon anticon-backward"></i> Trở lại
                                                </a>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </tbody>
                </table>

                <!-- Pagination -->
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        @if (PageCurrent > 1)
                        {
                            <li class="page-item">
                                <a class="page-link" href="?id=@ViewBag.Hotelid&Page=1" aria-label="Previous">
                                    <span class="fa fa-chevron-left"></span>
                                </a>
                            </li>
                            if (PageNextMinus >= 1)
                            {
                                <li class="page-item"><a class="page-link" href="?id=@ViewBag.Hotelid&Page=@PageNextMinus">@PageNextMinus</a></li>
                            }
                            <li class="page-item"><a class="page-link" href="?id=@ViewBag.Hotelid&Page=@PageBack">@PageBack</a></li>
                        }
                        else
                        {
                            <li class="page-item disabled">
                                <a class="page-link" href="?id=@ViewBag.Hotelid&Page=1" aria-label="Previous">
                                    <span class="fa fa-chevron-left"></span>
                                </a>
                            </li>
                        }

                        <li class="page-item active"><a class="page-link" href="?id=@ViewBag.Hotelid&Page=@PageCurrent">@PageCurrent</a></li>

                        @if (PageCurrent < PageLength)
                        {
                            <li class="page-item"><a class="page-link" href="?id=@ViewBag.Hotelid&Page=@PageNext">@PageNext</a></li>

                            if (PageNextPlus <= PageLength)
                            {
                                <li class="page-item"><a class="page-link" href="?id=@ViewBag.Hotelid&Page=@PageNextPlus">@PageNextPlus</a></li>
                            }
                            <li class="page-item">
                                <a class="page-link" href="?id=@ViewBag.Hotelid&Page=@PageLength" aria-label="Next">
                                    <span class="fa fa-chevron-right"></span>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="page-item disabled">
                                <a class="page-link" href="?id=@ViewBag.Hotelid&Page=1" aria-label="Next">
                                    <span class="fa fa-chevron-right"></span>
                                </a>
                            </li>
                        }

                    </ul>
                </nav>
                <!-- End Pagination -->

            </div>
        </div>
    </div>
</div>