Travel/Travel/Travel/Areas/Admin/Controllers/AdminHotelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using Travel.Models;
using Travel.Areas.Admin.Models;

namespace Travel.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class AdminHotelsController : Controller
    {
        private readonly dbTravelAndHotelContext _context;
        public INotyfService _notyfService { get; }

        public AdminHotelsController(dbTravelAndHotelContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminHotels
        public IActionResult Index(int page = 1)
        {
            var pageNumber = page;
            var pageSize = 10;

            List<Hotel> lsHotels = new List<Hotel>();

            lsHotels = _context.Hotels
                .AsNoTracking()
                .OrderBy(x => x.HotelId)
                .ToList();

            PagedList<Hotel> models = new PagedList<Hotel>(lsHotels.AsQueryable(), pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            ViewBag.PageLength = (int)Math.Ceiling((Double)lsHotels.Count / (Double)pageSize);
            return View(models);
        }

        // GET: Admin/AdminHotels/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null || _context.Hotels == null)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return RedirectToAction(nameof(Index));
            }
            HotelViewModel hotelVM = new HotelViewModel();

            hotelVM.lsHotel = new Hotel();
            hotelVM.lsImgHotel = new List<ImgHotel>();
            hotelVM.lsTypeRoom = new List<TypeRoom>();

            hotelVM.lsHotel = _context.Hotels
                .FirstOrDefault(m => m.HotelId == id);

            hotelVM.lsImgHotel = _context.ImgHotels
                .AsNoTracking()
                .Include(x => x.Hotel)
                .OrderBy(x=>x.ImgHotelId)
                .Where(x=>x.HotelId == id)
                .ToList();

            hotelVM.lsTypeRoom = _context.TypeRooms
                .AsNoTracking()
                .Include(x=>x.Hotel)
                .OrderBy(x=>x.TypeId)
                .Where(x=>x.HotelId == id)
                .ToList();

            if (hotelVM.lsHotel == null)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return RedirectToAction(nameof(Index));
            }

            return View(hotelVM);
        }

        // GET: Admin/AdminHotels/Create
        public IActionResult Create()
        {
            _notyfService.Information("Bạn đang tạo mới");
            return View();
        }

        // POST: Admin/AdminHotels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HotelId,Name,Phone")] Hotel hotel)
        {
            if (ModelState.IsValid && hotel.Name != null && hotel.Phone.Length == 10)
            {
                _context.Add(hotel);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thành công");
                return RedirectToAction(nameof(Index));
            }
            _notyfService.Warning("Vui lòng kiểm tra lại");
            return View(hotel);
        }

        // GET: Admin/AdminHotels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Hotels == null)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return RedirectToAction(nameof(Index));
            }

            var hotel = await _context.Hotels.FindAsync(id);
            if (hotel == null)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return RedirectToAction(nameof(Index));
            }
            _notyfService.Information("Bạn đang chỉnh sửa");
            return View(hotel);
        }

        // POST: Admin/AdminHotels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HotelId,Name,Phone")] Hotel hotel)
        {
            if (id != hotel.HotelId)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return RedirectToAction(nameof(Index));
            }

            if (ModelState.IsValid && hotel.Name != null && hotel.Phone.Length == 10)
            {
                try
                {
                    _context.Update(hotel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HotelExists(hotel.HotelId))
                    {
                        _notyfService.Error("Đã xảy ra lỗi");
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        throw;
                    }
                }
                _notyfService.Success("Thành công");
                return RedirectToAction(nameof(Index));
            }
            _notyfService.Warning("Vui lòng kiểm tra lại");
            return View(hotel);
        }

        // GET: Admin/AdminHotels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Hotels == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotels
                .FirstOrDefaultAsync(m => m.HotelId == id);
            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }

        // POST: Admin/AdminHotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Hotels == null)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return RedirectToAction(nameof(Index));
            }
            var hotel = await _context.Hotels.FindAsync(id);
            if (hotel != null)
            {
                if (await _context.HotelBookings.FirstOrDefaultAsync(x => x.HotelId == hotel.HotelId) != null)
                {
                    _notyfService.Error("Đã xảy ra lỗi");
                    return RedirectToAction(nameof(Index));
                }

                _context.Hotels.Remove(hotel);
            }
            
            await _context.SaveChangesAsync();
            _notyfService.Success("Thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool HotelExists(int id)
        {
          return _context.Hotels.Any(e => e.HotelId == id);
        }
    }
}

Travel/Travel/Travel/Areas/Admin/Views/AdminHotels/Create.cshtml
@model Travel.Models.Hotel

@{
    ViewData["Title"] = "Thêm mới";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-action="Index" asp-controller="Home" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ quản trị</a>
            <a asp-action="Index" asp-controller="AdminHotels" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home"></i>Khách sạn</a>
            <span class="breadcrumb-item active"><i class="anticon anticon-plus-circle"></i> @ViewData["Title"]</span>
        </nav>
    </div>
</div>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Tên khách sạn</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label">Số điện thoại</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>

            <div class="form-row">
                <div class="btn-group">
                    <button class="btn btn-success btn-tone m-r-5">
                        <i class="anticon anticon-save"></i>
                        <span>Lưu</span>
                    </button>

                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminHotels" asp-action="Index">
                        <i class="anticon anticon-backward"></i> Trở lại
                    </a>
                </div>
            </div>

        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Travel/Travel/Travel/Areas/Admin/Views/AdminHotels/Delete.cshtml
@model Travel.Models.Hotel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hotel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="HotelId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Travel/Travel/Travel/Areas/Admin/Views/AdminHotels/Details.cshtml
@model Travel.Areas.Admin.Models.HotelViewModel;

@{
    ViewData["Title"] = "Mô tả chi tiết";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-action="Index" asp-controller="Home" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ quản trị</a>
            <a asp-action="Index" asp-controller="AdminHotels" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home"></i> Quản lý khách sạn</a>
            <span class="breadcrumb-item active"><i class="anticon anticon-plus-circle"></i> @ViewData["Title"]</span>
        </nav>
    </div>
</div>


<form>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
                <div class="m-l-15">
                    <h4>Khách Sạn </h4>
                    @Html.DisplayFor(model => model.lsHotel.Name)
                </div>
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.lsHotel.HotelId">
                    <i class="anticon anticon-save"></i>
                    <span>Chỉnh sửa</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#imghotel">Hình ảnh</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#infoHotel&Tour">Thông tin khách hàng và tour của họ</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#Room">Phòng</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold">ID Khách Sạn</label><br />
                        <p>@Html.DisplayFor(model => model.lsHotel.HotelId)</p>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">Tên Khách Sạn</label><br />
                        <p>@Html.DisplayFor(model => model.lsHotel.Name)</p>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">Địa Chỉ</label><br />
                        <p>Ninh Kiều</p>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">Số điện thoại</label><br />
                        <p>@Html.DisplayFor(model => model.lsHotel.Phone)</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade show" id="imghotel">
            <a href="/admin/AdminImgHotels?id=@Model.lsHotel.HotelId">
                <span class="icon-holder">
                    <i class="anticon anticon-picture"></i>
                </span>
                <span class="title">Quản lý hình ảnh khách sạn</span>
            </a>
            <div class="row">
            @foreach (var item in Model.lsImgHotel)
            {
                
                    <div class="col-lg-3">

                        <div class="card">
                            <div class="card-body">
                                <img width="250px" src="~/images/ImgHotels/@item.Description" alt="@item.ImgHotelId" />
                            </div>
                        </div>
                    </div>
           
            }
            </div>
        </div>
    </div>
</form>

Travel/Travel/Travel/Areas/Admin/Views/AdminHotels/Edit.cshtml
@model Travel.Models.Hotel

@{
    ViewData["Title"] = "Chỉnh sửa";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-action="Index" asp-controller="Home" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ quản trị</a>
            <a asp-action="Index" asp-controller="AdminHotels" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home"></i>Khách sạn</a>
            <span class="breadcrumb-item active"><i class="anticon anticon-edit"></i> @ViewData["Title"]</span>
        </nav>
    </div>
</div>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="HotelId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Tên khách sạn</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label">Số điện thoại</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>

            <div class="form-row">
                <div class="btn-group">
                    <button class="btn btn-success btn-tone m-r-5">
                        <i class="anticon anticon-save"></i>
                        <span>Lưu</span>
                    </button>

                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminHotels" asp-action="Index">
                        <i class="anticon anticon-backward"></i> Trở lại
                    </a>
                </div>
            </div>

        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Travel/Travel/Travel/Areas/Admin/Views/AdminHotels/Index.cshtml
@using PagedList.Core.Mvc
@model IEnumerable<Travel.Models.Hotel>

@{
    ViewData["Title"] = "Khách sạn";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    int PageCurrent = ViewBag.CurrentPage;
    int PageLength = ViewBag.PageLength;
    int PageBack = PageCurrent - 1;
    int PageNext = PageCurrent + 1;
    int PageNextPlus = PageNext + 1;
    int PageNextMinus = PageBack - 1;
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-action="Index" asp-controller="Home" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ quản trị</a>
            <span class="breadcrumb-item active"> <i class="anticon anticon-home"></i> @ViewData["Title"] (@PageCurrent/@PageLength trang)</span>
        </nav>
    </div>
</div>

<div class="text-center m-t-30 m-b-40">
    <a class="btn btn-success" asp-area="Admin" asp-controller="AdminHotels" asp-action="Create">
        <i class="anticon anticon-plus-circle m-r-5"></i> <span>Thêm mới</span>
    </a>
</div>


<div class="row">
    <div class="col-lg-11 mx-auto">
        <!-- Card View -->
        <div class="row" id="card-view">
            @foreach (var item in Model)
            {
                <div class="col-md-3">
                    <div class="card">
                        <div class="card-body">

                            <div class="m-t-20 text-center">
                                <div class="avatar avatar-image" style="height: 100px; width: 100px;">
                                    <img src="assets/images/avatars/thumb-1.jpg" alt="">
                                </div>
                                <h4 class="m-t-30">Tên Khách sạn</h4>
                                <a asp-area="Admin" asp-controller="AdminHotels" asp-action="Details" asp-route-id="@item.HotelId"> @item.Name</a>
                            </div>
                            <div class="text-center m-t-15">
                                @item.Phone
                            </div>
                            <div class="text-center m-t-30">
                                <a class="btn btn-warning btn-tone m-r-5" asp-area="Admin" asp-controller="AdminHotels" asp-action="Edit" asp-route-id="@item.HotelId">
                                    <i class="anticon anticon-edit"></i> Sửa
                                </a>

                                <a class="btn btn-danger btn-tone m-r-5" data-toggle="modal" data-target="#Modal_@item.HotelId">
                                    <i class="anticon anticon-delete"></i>Xóa
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>

<!-- Pagination -->
<nav aria-label="Page navigation">
    <ul class="pagination">
        @if (PageCurrent > 1)
        {
            <li class="page-item">
                <a class="page-link" href="?Page=1" aria-label="Previous">
                    <span class="fa fa-chevron-left"></span>
                </a>
            </li>
            if (PageNextMinus >= 1)
            {
                <li class="page-item"><a class="page-link" href="?Page=@PageNextMinus">@PageNextMinus</a></li>
            }
            <li class="page-item"><a class="page-link" href="?Page=@PageBack">@PageBack</a></li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" href="?Page=1" aria-label="Previous">
                    <span class="fa fa-chevron-left"></span>
                </a>
            </li>
        }

        <li class="page-item active"><a class="page-link" href="?Page=@PageCurrent">@PageCurrent</a></li>

        @if (PageCurrent < PageLength)
        {
            <li class="page-item"><a class="page-link" href="?Page=@PageNext">@PageNext</a></li>

            if (PageNextPlus <= PageLength)
            {
                <li class="page-item"><a class="page-link" href="?Page=@PageNextPlus">@PageNextPlus</a></li>
            }
            <li class="page-item">
                <a class="page-link" href="?Page=@PageLength" aria-label="Next">
                    <span class="fa fa-chevron-right"></span>
                </a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" href="?Page=1" aria-label="Next">
                    <span class="fa fa-chevron-right"></span>
                </a>
            </li>
        }

    </ul>
</nav>
<!-- End Pagination -->


    