Travel/Travel/Travel/Areas/Admin/Controllers/AdminPlacesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using Travel.Models;

namespace Travel.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class AdminPlacesController : Controller
    {
        private readonly dbTravelAndHotelContext _context;

        public INotyfService _notyfService { get; }

        public AdminPlacesController(dbTravelAndHotelContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminPlaces
        public IActionResult Index(int page = 1)
        {
            var pageNumber = page;
            var pageSize = 10;

            List<Place> lsPlaces = new List<Place>();

            lsPlaces = _context.Places
                .AsNoTracking()
                .OrderBy(x => x.PlaceId)
                .Include(x => x.Location)
                .ToList();

            PagedList<Place> models = new PagedList<Place>(lsPlaces.AsQueryable(), pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            ViewBag.PageLength = (int)Math.Ceiling((Double)lsPlaces.Count / (Double)pageSize);
            return View(models);
        }

        // GET: Admin/AdminPlaces/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Places == null)
            {
                _notyfService.Warning("Vui lòng kiểm tra lại");
                return RedirectToAction(nameof(Index));
            }

            var place = await _context.Places
                .Include(p => p.Location)
                .FirstOrDefaultAsync(m => m.PlaceId == id);
            if (place == null)
            {
                _notyfService.Warning("Vui lòng kiểm tra lại");
                return RedirectToAction(nameof(Index));
            }

            return View(place);
        }

        // GET: Admin/AdminPlaces/Create
        public IActionResult Create()
        {
            ViewData["LocationId"] = new SelectList(_context.Location1s, "LocationId", "Name");
            _notyfService.Information("Bạn đang tạo mới");
            return View();
        }

        // POST: Admin/AdminPlaces/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlaceId,Name,Address,Image,LocationId")] Place place)
        {
            if (ModelState.IsValid && place.Name != null && place.LocationId != null)
            {
                _context.Add(place);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationId"] = new SelectList(_context.Location1s, "LocationId", "Name", place.LocationId);
            _notyfService.Warning("Vui lòng kiểm tra lại");
            return View(place);
        }

        // GET: Admin/AdminPlaces/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Places == null)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return RedirectToAction(nameof(Index));
            }

            var place = await _context.Places.FindAsync(id);
            if (place == null)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationId"] = new SelectList(_context.Location1s, "LocationId", "Name", place.LocationId);
            _notyfService.Information("Bạn đang chỉnh sửa");
            return View(place);
        }

        // POST: Admin/AdminPlaces/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PlaceId,Name,Address,Image,LocationId")] Place place)
        {
            if (id != place.PlaceId)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return RedirectToAction(nameof(Index));
            }

            if (ModelState.IsValid && place.Name != null && place.LocationId != null)
            {
                try
                {
                    _context.Update(place);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlaceExists(place.PlaceId))
                    {
                        _notyfService.Error("Đã xảy ra lỗi");
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        throw;
                    }
                }
                _notyfService.Success("Thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationId"] = new SelectList(_context.Location1s, "LocationId", "Name", place.LocationId);
            _notyfService.Warning("Vui lòng kiểm tra lại");
            return View(place);
        }

        // GET: Admin/AdminPlaces/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Places == null)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return RedirectToAction(nameof(Index));
            }

            var place = await _context.Places
                .Include(p => p.Location)
                .FirstOrDefaultAsync(m => m.PlaceId == id);
            if (place == null)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return RedirectToAction(nameof(Index));
            }
            _notyfService.Success("Thành công");
            return View(place);
        }

        // POST: Admin/AdminPlaces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Places == null)
            {
                _notyfService.Error("Đã xảy ra lỗi");
                return RedirectToAction(nameof(Index));
            }
            var place = await _context.Places.FindAsync(id);



            if (place != null)
            {
                if (await _context.Tours.FirstOrDefaultAsync(x => x.PlaceId == place.PlaceId) != null)
                {
                    _notyfService.Error("Đã xảy ra lỗi");
                    return RedirectToAction(nameof(Index));
                }
                _context.Places.Remove(place);
            }
            
            await _context.SaveChangesAsync();
            _notyfService.Success("Thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool PlaceExists(int id)
        {
          return _context.Places.Any(e => e.PlaceId == id);
        }
    }
}

Travel/Travel/Travel/Areas/Admin/Views/AdminPlaces/Create.cshtml
@model Travel.Models.Place

@{
    ViewData["Title"] = "Thêm mới";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-action="Index" asp-controller="Home" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ quản trị</a>
            <a asp-action="Index" asp-controller="AdminPlaces" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-environment"></i>Địa điểm</a>
            <span class="breadcrumb-item active"><i class="anticon anticon-plus-circle"></i> @ViewData["Title"]</span>
        </nav>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Tên Địa Điểm</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label">Địa Chỉ</label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label">Hình Ảnh</label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label">Quận/Huyện</label>
                <select asp-for="LocationId" class ="form-control" asp-items="ViewBag.LocationId"></select>
            </div>


            <div class="form-row">
                <div class="btn-group">
                    <button class="btn btn-success btn-tone m-r-5">
                        <i class="anticon anticon-save"></i>
                        <span>Lưu</span>
                    </button>

                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPlaces" asp-action="Index">
                        <i class="anticon anticon-backward"></i> Trở lại
                    </a>
                </div>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Travel/Travel/Travel/Areas/Admin/Views/AdminPlaces/Delete.cshtml
@model Travel.Models.Place

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Place</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PlaceId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Travel/Travel/Travel/Areas/Admin/Views/AdminPlaces/Details.cshtml
@model Travel.Models.Place

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Place</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PlaceId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Travel/Travel/Travel/Areas/Admin/Views/AdminPlaces/Edit.cshtml
@model Travel.Models.Place

@{
    ViewData["Title"] = "Chỉnh sửa";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-action="Index" asp-controller="Home" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ quản trị</a>
            <a asp-action="Index" asp-controller="AdminPlaces" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-environment"></i> Địa điểm</a>
            <span class="breadcrumb-item active"><i class="anticon anticon-edit"></i> @ViewData["Title"]</span>
        </nav>
    </div>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PlaceId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Tên Địa Điểm</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label">Địa Chỉ</label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label">Hình Ảnh</label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label">Quận/Huyện</label>
                <select asp-for="LocationId" class="form-control" asp-items="ViewBag.LocationId"></select>
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="btn-group">
                    <button class="btn btn-success btn-tone m-r-5">
                        <i class="anticon anticon-save"></i>
                        <span>Lưu</span>
                    </button>

                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPlaces" asp-action="Index">
                        <i class="anticon anticon-backward"></i> Trở lại
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Travel/Travel/Travel/Areas/Admin/Views/AdminPlaces/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<Travel.Models.Place>

@{
    ViewData["Title"] = "Địa điểm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    int PageCurrent = ViewBag.CurrentPage;
    int PageLength = ViewBag.PageLength;
    int PageBack = PageCurrent - 1;
    int PageNext = PageCurrent + 1;
    int PageNextPlus = PageNext + 1;
    int PageNextMinus = PageBack - 1;
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-action="Index" asp-controller="Home" asp-area="admin" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ quản trị</a>
            <span class="breadcrumb-item active"><i class="anticon anticon-environment"></i> @ViewData["Title"] (@PageCurrent/@PageLength trang)</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">

        <div class="m-t-25">
            <div class="table-responsive">
                <a class="btn btn-success" asp-area="Admin" asp-controller="AdminPlaces" asp-action="Create">
                    <i class="anticon anticon-plus-circle m-r-5"></i> <span>Thêm mới</span>
                </a>
                <table class="table">
                    <thead class="text-center">
                        <tr>
                            <th scope="col">Tên địa điểm</th>
                            <th scope="col">Hình ảnh</th>
                            <th scope="col">Địa chỉ</th>
                            <th scope="col">#</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">@item.Name</th>

                                <td>@item.Image</td>
                                <td>@item.Address, @item.Location.Type @item.Location.Name</td>
                                <td>
                                    <a class="btn btn-warning btn-tone m-r-5" asp-area="Admin" asp-controller="AdminPlaces" asp-action="Edit" asp-route-id="@item.PlaceId">
                                        <i class="anticon anticon-edit"></i> Sửa
                                    </a>

                                    <a class="btn btn-danger btn-tone m-r-5" data-toggle="modal" data-target="#Modal_@item.PlaceId">
                                        <i class="anticon anticon-delete"></i>Xóa
                                    </a>
                                </td>
                            </tr>

                            <!-- Modal -->
                            <div class="modal fade" id="Modal_@item.PlaceId">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="ModalLabel">Bạn có chắc chắn muốn xóa</h5>
                                            <button type="button" class="close" data-dismiss="modal">
                                                <i class="anticon anticon-close"></i>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            Tên địa điểm: @item.Name
                                        </div>
                                        <div class="modal-footer">
                                            <form asp-action="Delete" asp-controller="AdminPlaces" asp-area="Admin" asp-route-id="@item.PlaceId">
                                                <input type="hidden" />

                                                <button type="submit" value="Delete" class="btn btn-danger btn-tone m-r-5">
                                                    <i class="anticon anticon-delete"></i>
                                                    <span>Xóa</span>
                                                </button>

                                                <a class="btn btn-primary btn-tone m-r-5" data-dismiss="modal">
                                                    <i class="anticon anticon-backward"></i> Trở lại
                                                </a>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </tbody>
                </table>

                <!-- Pagination -->
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        @if (PageCurrent > 1)
                        {
                            <li class="page-item">
                                <a class="page-link" href="?Page=1" aria-label="Previous">
                                    <span class="fa fa-chevron-left"></span>
                                </a>
                            </li>
                            if (PageNextMinus >= 1)
                            {
                                <li class="page-item"><a class="page-link" href="?Page=@PageNextMinus">@PageNextMinus</a></li>
                            }
                            <li class="page-item"><a class="page-link" href="?Page=@PageBack">@PageBack</a></li>
                        }
                        else
                        {
                            <li class="page-item disabled">
                                <a class="page-link" href="?Page=1" aria-label="Previous">
                                    <span class="fa fa-chevron-left"></span>
                                </a>
                            </li>
                        }

                        <li class="page-item active"><a class="page-link" href="?Page=@PageCurrent">@PageCurrent</a></li>

                        @if (PageCurrent < PageLength)
                        {
                            <li class="page-item"><a class="page-link" href="?Page=@PageNext">@PageNext</a></li>

                            if (PageNextPlus <= PageLength)
                            {
                                <li class="page-item"><a class="page-link" href="?Page=@PageNextPlus">@PageNextPlus</a></li>
                            }
                            <li class="page-item">
                                <a class="page-link" href="?Page=@PageLength" aria-label="Next">
                                    <span class="fa fa-chevron-right"></span>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="page-item disabled">
                                <a class="page-link" href="?Page=1" aria-label="Next">
                                    <span class="fa fa-chevron-right"></span>
                                </a>
                            </li>
                        }

                    </ul>
                </nav>
                <!-- End Pagination -->

            </div>
        </div>
    </div>
</div>